version: "3"

services:
  calculator:
    build:
      context: Calculator
      dockerfile: Dockerfile
    image: calculator
    container_name: calculator
    restart: unless-stopped

  hello-world:
    image: hello-world
    container_name: hello-world
    restart: unless-stopped

  file-writer:
    build:
      context: FileWriter 
      dockerfile: Dockerfile
    image: file-writer
    container_name: file-writer
    restart: unless-stopped

  static-webpage:
    build:
      context: StaticWebpage 
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    image: static-webpage
    container_name: static-webpage
    restart: unless-stopped
