name: deploy
on: 
  push:
    branches: [main]
#  workflow_dispatch: # uncomment this line and comment above to disable deploy on push
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              cd Lecture6
              git pull
